//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacenamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Almacenamiento()
        {
            this.Ensamble = new HashSet<Ensamble>();
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "ID Almacenamiento")]
        public int idAlmacenamento { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Nombre")]
        public string nombre { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Tipo")]
        public string tipo { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Capacidad")]
        public string capacidad { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Costo con proveedor")]
        public double costoProveedor { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Costo a venta")]
        public double costoVenta { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Marca")]
        public string marca { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Watts")]
        public double watts { get; set; }
        public Nullable<double> RPM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ensamble> Ensamble { get; set; }
    }
}
