//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuelloBotella
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Cuello de botella")]
        public int idCuelloBotella { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Ensamble")]
        public int idEnsamble_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Procesador")]
        public int idProcesador_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Modelo")]
        public string modelo { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Comentarios")]
        public string comnetarios { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Tarjeta de Video")]
        public int idTarjetaVideo_FK { get; set; }
    
        public virtual Ensamble Ensamble { get; set; }
        public virtual procesador procesador { get; set; }
        public virtual tarjetaVideo tarjetaVideo { get; set; }
    }
}
