//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ensamble
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ensamble()
        {
            this.cuelloBotella = new HashSet<cuelloBotella>();
            this.Perfil_Ensamble = new HashSet<Perfil_Ensamble>();
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "ID Ensamble")]
        public int idEnsamble { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Placa madre")]
        public int idPlacaMadre_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Procesador")]
        public int idProcesador_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID RAM")]
        public int idRAM_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Almacenamiento")]
        public int idAlmacenamiento_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Fuente de poder")]
        public int idFuentePoder_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Tarjeta de Video")]
        public int idTarjetaVideo_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Gabinete")]
        public int idGabinete_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Empleado")]
        public int idEmpleado_FK { get; set; }
    
        public virtual Almacenamiento Almacenamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cuelloBotella> cuelloBotella { get; set; }
        public virtual fuentePoder fuentePoder { get; set; }
        public virtual Gabinete Gabinete { get; set; }
        public virtual LogEmpleado LogEmpleado { get; set; }
        public virtual memoriaRAM memoriaRAM { get; set; }
        public virtual modeloVideo modeloVideo { get; set; }
        public virtual PlacaMadre PlacaMadre { get; set; }
        public virtual procesador procesador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfil_Ensamble> Perfil_Ensamble { get; set; }
    }
}
