//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gabinete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gabinete()
        {
            this.Ensamble = new HashSet<Ensamble>();
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "ID Gabinete")]
        public int idGabinete { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Costo con proveedor")]
        public double costoProveedor { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Costo a venta")]
        public double costoVenta { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Marca")]
        public string marca { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Modelo")]
        public string modelo { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Medida")]
        public string medida { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ensamble> Ensamble { get; set; }
    }
}
