//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneracionSoportadaPlacaMadre
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "Generación soportada por tarjeta madre")]
        public int idGeneracionSoportadaPlacaMadre { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Tarjeta madre")]
        public int idPlacaMadre_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Generación del procesador")]
        public int idGeneracionProcesador_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
    
        public virtual detalleGeneracionProcesador detalleGeneracionProcesador { get; set; }
        public virtual PlacaMadre PlacaMadre { get; set; }
    }
}
