//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEmpleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogEmpleado()
        {
            this.Ensamble = new HashSet<Ensamble>();
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "ID Empleado")]
        public int idEmpleado { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Ensamble")]
        public int idEnsamble { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Fecha")]
        public System.DateTime fecha { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Usuario")]
        public int idUsuario_FK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ensamble> Ensamble { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
