//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil_Ensamble
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Perfil de ensamble")]
        public int idPerfil_Ensamble { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Perfil")]
        public int idPerfil_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Ensamble")]
        public int idEnsamble_FK { get; set; }
    
        public virtual Ensamble Ensamble { get; set; }
        public virtual Perfiles Perfiles { get; set; }
    }
}
