//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Perfiles()
        {
            this.Perfil_Ensamble = new HashSet<Perfil_Ensamble>();
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "ID Perfil")]
        public int idPerfil { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Nombre del perfil")]
        public string Nombre { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Nivel del perfil")]
        public string Nivel { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "ID Ensamble")]
        public int idEnsamble_FK { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public Nullable<bool> estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Perfil_Ensamble> Perfil_Ensamble { get; set; }
    }
}
