//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }

        [System.ComponentModel.DataAnnotations.Display(Name = "ID Persona")]
        public int idPersona { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Nombre")]
        public string nombre { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Apellido paterno")]
        public string apePaterno { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Apellido materno")]
        public string apeMaterno { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Edad")]
        public Nullable<int> edad { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Dirección")]
        public string direccion { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
