//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_usuarios
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "ID tipo de usuario")]
        public int id { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Descripción")]
        public string descripcion { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public bool estatus { get; set; }
    }
}
