//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRP_RatboyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URLImagenes
    {
        [System.ComponentModel.DataAnnotations.Display(Name = "ID URL IMAGE")]
        public int idUrl { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Tipo")]
        public string tipo { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "URL")]
        public string URL { get; set; }
        [System.ComponentModel.DataAnnotations.Display(Name = "Estatus")]
        public Nullable<bool> estatus { get; set; }
    }
}
